SELECT * FROM
  CONTR LEFT OUTER JOIN PERS ON (CONTR.PERS_ID = PERS.PERS_ID)
  INNER JOIN (SELECT * FROM DEPART WHERE 1500 BETWEEN DEPART.MIN_SALARY AND DEPART.MAX_SALARY)
    ON (depart.depart_id = contr.depart_id);

SELECT * FROM
  CONTR LEFT OUTER JOIN PERS ON (CONTR.PERS_ID = PERS.PERS_ID),
  (SELECT * FROM DEPART WHERE 1500 BETWEEN DEPART.MIN_SALARY AND DEPART.MAX_SALARY)
    WHERE CONTR.DEPART_ID = DEPART.DEPART_ID;