CREATE TABLE TEST2
(
  ID      	NUMBER        CONSTRAINT PK_ID   	     PRIMARY KEY,
  PARENT_ID	NUMBER        CONSTRAINT FK_PARENT_ID 	REFERENCES TEST2 (ID),
  STR		   VARCHAR2(255),
  CONSTRAINT str_ CHECK (STR NOT LIKE '%99%'),
  CONSTRAINT chk_id_parent CHECK (ID <> PARENT_ID)
)
/
